export const FETCH_CONTENTS = 'FETCH_CONTENTS'
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS'
export const FETCH_CONTENTS_FAILURE = 'FETCH_CONTENTS_FAILURE'

export const TOGGLE_BOX = 'TOGGLE_BOX'
export const GO_TO_PAGE = 'GO_TO_PAGE'


